namespace DataGenerationUseCase23.Models
{
    public class AgeCertification
    {
        public enum AgeCertificationEnum
        {
            G,
            PG,
            PG13,
            R,
            NC17,
            U,
            UA,
            A,
            S,
            AL,
            Six,
            Nine,
            Twenty,
            TwentyA,
            Fifty,
            Eighty,
            EightyR,
            R18,
            R21,
            M,
            MA15Plus,
            R16,
            R18Plus,
            X18,
            T,
            E,
            E10Plus,
            EC,
            C,
            CA,
            GP,
            MPG,
            TVY,
            TVY7,
            TVG,
            TVPG,
            TV14,
            TVMA,
        }

        public Dictionary<AgeCertificationEnum, string> AgeCertificationDictionary = new() {
            { AgeCertificationEnum.G, "G" },
            { AgeCertificationEnum.PG, "PG" },
            { AgeCertificationEnum.PG13, "PG-13" },
            { AgeCertificationEnum.R, "R" },
            { AgeCertificationEnum.NC17, "NC-17" },
            { AgeCertificationEnum.U, "U" },
            { AgeCertificationEnum.UA, "U/A" },
            { AgeCertificationEnum.A, "A" },
            { AgeCertificationEnum.S, "S" },
            { AgeCertificationEnum.AL, "AL" },
            { AgeCertificationEnum.Six, "6" },
            { AgeCertificationEnum.Nine, "9" },
            { AgeCertificationEnum.Twenty, "12" },
            { AgeCertificationEnum.TwentyA, "12A" },
            { AgeCertificationEnum.Fifty, "15" },
            { AgeCertificationEnum.Eighty, "18" },
            { AgeCertificationEnum.EightyR, "18R" },
            { AgeCertificationEnum.R18, "R18" },
            { AgeCertificationEnum.R21, "R21" },
            { AgeCertificationEnum.M, "M" },
            { AgeCertificationEnum.MA15Plus, "MA15+" },
            { AgeCertificationEnum.R16, "R16" },
            { AgeCertificationEnum.R18Plus, "R18+" },
            { AgeCertificationEnum.X18, "X18" },
            { AgeCertificationEnum.T, "T" },
            { AgeCertificationEnum.E, "E" },
            { AgeCertificationEnum.E10Plus, "E10+" },
            { AgeCertificationEnum.EC, "EC" },
            { AgeCertificationEnum.C, "C" },
            { AgeCertificationEnum.CA, "CA" },
            { AgeCertificationEnum.GP, "GP" },
            { AgeCertificationEnum.MPG, "M/PG" },
            { AgeCertificationEnum.TVY, "TV-Y" },
            { AgeCertificationEnum.TVY7, "TV-Y7" },
            { AgeCertificationEnum.TVG, "TV-G" },
            { AgeCertificationEnum.TVPG, "TV-PG" },
            { AgeCertificationEnum.TV14, "TV-14" },
            { AgeCertificationEnum.TVMA, "TV-MA" }
        };
    }
}
